#!/usr/bin/env bash

# dependencies:
#   - bash >= v4 - for use of associative array(s)

# --------------------------------------------------------------------------------------------------------------
# ansible does support running a script to derive a password but does not support using a variable directly. 
# with that in mind, this script simply echos a variable that should be already set from some other more secure place.
# --------------------------------------------------------------------------------------------------------------
# if [ "$ANSIBLE_VAULT_PASSWORD" ] ; then
#   echo -n "$ANSIBLE_VAULT_PASSWORD"
# else
#   echo -n 'Vault password: ' > /dev/tty; read -s p
#   echo -n "$p"
# fi

# --------------------------------------------------------------------------------------------------------------
[ "$ANSIBLE_VAULT_PASSWORD" ] && echo -n "$ANSIBLE_VAULT_PASSWORD"
exit 0

# opts=$(getopt -o v --long vault-id: -- "$@")
opts=$(getopt v: $*)
set -- $opts

echo opts: $opts
echo args: $*

exit 0








declare -A ANSIBLE_VAULT_PASSWORD

key=default
[ "$1" ] && key="$1"

# ANSIBLE_VAULT_PASSWORD=fu

ANSIBLE_VAULT_PASSWORD["a"]="foo"
ANSIBLE_VAULT_PASSWORD["b"]="bar"
ANSIBLE_VAULT_PASSWORD["a b"]="abc"
ANSIBLE_VAULT_PASSWORD[default]="xyz"

# note: use variable (i.e. vault-id) as key and use 'default' if no key provided

echo ANSIBLE_VAULT_PASSWORD: ${ANSIBLE_VAULT_PASSWORD}
echo ANSIBLE_VAULT_PASSWORD\[a\]: ${ANSIBLE_VAULT_PASSWORD[a]}
echo ANSIBLE_VAULT_PASSWORD\[b\]: ${ANSIBLE_VAULT_PASSWORD[b]}
echo ANSIBLE_VAULT_PASSWORD\[a b\]: ${ANSIBLE_VAULT_PASSWORD[a b]}
echo ANSIBLE_VAULT_PASSWORD\[default\]: ${ANSIBLE_VAULT_PASSWORD[default]}
echo ANSIBLE_VAULT_PASSWORD\[\$key\]: ${ANSIBLE_VAULT_PASSWORD["$key"]}
echo ANSIBLE_VAULT_PASSWORD\['@'\]: ${ANSIBLE_VAULT_PASSWORD[@]}

echo ''
echo ANSIBLE_VAULT_PASSWORD\[\$SUBENV\]: ${ANSIBLE_VAULT_PASSWORD[$SUBENV]}

if [ "$ANSIBLE_VAULT_PASSWORD[$vaultid]" ]; then
  echo -n "$ANSIBLE_VAULT_PASSWORD[$vaultid]"
elif [ "$ANSIBLE_VAULT_PASSWORD[$SUBENV]" ]; then
  echo -n "$ANSIBLE_VAULT_PASSWORD[$SUBENV]"
elif [ "$ANSIBLE_VAULT_PASSWORD[default]" ]; then
  echo -n "$ANSIBLE_VAULT_PASSWORD[default]"
elif [ "$ANSIBLE_VAULT_PASSWORD" ]; then
  echo -n "$ANSIBLE_VAULT_PASSWORD"
else
  echo -n 'Vault password: ' > /dev/tty; read -s p; echo -n "$p"
fi



